FROM nvidia/cuda:10.0-devel-ubuntu18.04

# Settings
ENV DEBIAN_FRONTEND noninteractive
ENV CUDNN_VERSION 7.6.2.24
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

# Install essential libraries
RUN apt update
RUN apt upgrade -y
RUN apt install -y --no-install-recommends \
      libcudnn7=$CUDNN_VERSION-1+cuda10.0 \
      libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0
RUN apt install -y --no-install-recommends \
      bash-completion curl ca-certificates
RUN apt install -y --no-install-recommends \
      git build-essential \
      libffi-dev libssl-dev zlib1g-dev \
      libbz2-dev libreadline-dev libsqlite3-dev
RUN apt clean -y

# Install pyenv
RUN curl -L https://pyenv.run | /bin/bash

ENV PYTHON_VER 3.6.10
ENV PYENV_ROOT /root/.pyenv
ENV PATH $PYENV_ROOT/bin:$PATH

RUN pyenv install $PYTHON_VER
RUN pyenv global $PYTHON_VER
ENV PATH $PYENV_ROOT/versions/$PYTHON_VER/bin:$PATH
ENV LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:$PYENV_ROOT/versions/$PYTHON_VER/lib
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

# Setting for jupyter
RUN mkdir /root/.jupyter
RUN touch /root/.jupyter/jupyter_notebook_config.py
RUN echo 'c.NotebookApp.allow_root = True' >> /root/.jupyter/jupyter_notebook_config.py
RUN echo 'c.NotebookApp.ip = "0.0.0.0"' >> /root/.jupyter/jupyter_notebook_config.py
RUN echo 'c.NotebookApp.open_browser = False' >> /root/.jupyter/jupyter_notebook_config.py
RUN echo 'c.NotebookApp.token = ""' >> /root/.jupyter/jupyter_notebook_config.py

# Install essential python libraries
RUN pip install --no-cache-dir --upgrade pip setuptools
RUN pip install --no-cache-dir \
      tf-keras-vis==0.1.0 \
      tensorflow-gpu>=2.0.* \
      numpy scipy imageio pillow \
      jupyterlab matplotlib
