FROM ubuntu

# Settings
ENV DEBIAN_FRONTEND noninteractive

# Install essential libraries
RUN apt update
RUN apt upgrade -y
RUN apt install -y --no-install-recommends \
      bash-completion curl ca-certificates
RUN apt install -y --no-install-recommends \
      git build-essential \
      libffi-dev libssl-dev zlib1g-dev \
      libbz2-dev libreadline-dev libsqlite3-dev
RUN apt clean -y

# Install pyenv
RUN curl -L https://pyenv.run | /bin/bash

ENV PYTHON_VERSION 3.6.10
ENV PYENV_ROOT /root/.pyenv
ENV PATH $PYENV_ROOT/bin:$PATH

RUN pyenv install -v $PYTHON_VERSION
RUN pyenv global $PYTHON_VERSION
ENV PATH $PYENV_ROOT/versions/$PYTHON_VERSION/bin:$PATH
ENV LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:$PYENV_ROOT/versions/$PYTHON_VERSION/lib

# Setting for jupyter
RUN mkdir /root/.jupyter
RUN touch /root/.jupyter/jupyter_notebook_config.py
RUN echo 'c.NotebookApp.allow_root = True' >> /root/.jupyter/jupyter_notebook_config.py
RUN echo 'c.NotebookApp.ip = "0.0.0.0"' >> /root/.jupyter/jupyter_notebook_config.py
RUN echo 'c.NotebookApp.open_browser = False' >> /root/.jupyter/jupyter_notebook_config.py
RUN echo 'c.NotebookApp.token = ""' >> /root/.jupyter/jupyter_notebook_config.py

# Install essential python libraries
RUN pip install --no-cache-dir --upgrade pip setuptools
RUN pip install --no-cache-dir \
      tf-keras-vis==0.1.0 \
      tensorflow-cpu>=2.0.* \
      numpy scipy imageio pillow \
      jupyterlab matplotlib
